apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-role-binding
subjects:
  - kind: ServiceAccount
    name: controller-manageer
roleRef:
  kind: Role
  name: manager-role
  apiGroup: rbac.authorization.k8s.io